CREATE TABLE person (
  id      BIGSERIAL PRIMARY KEY,
  name    TEXT        NOT NULL,
  surname TEXT        NOT NULL,
  date    TIMESTAMPTZ NOT NULL DEFAULT now()
);


ALTER TABLE person
  ADD COLUMN status TEXT DEFAULT 'DISABLED' NOT NULL;

ALTER TABLE person
    ADD COLUMN first_visit BOOLEAN DEFAULT FALSE NOT NULL;

ALTER TABLE person
  ADD COLUMN nip TEXT;