/*
 * This file is generated by jOOQ.
*/
package co.aisystem.demoJooq.api.db.tables.records;


import co.aisystem.demoJooq.api.db.tables.DemographicTableRange;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.TableRecordImpl;
import org.jooq.lambda.tuple.Range;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DemographicTableRangeRecord extends TableRecordImpl<DemographicTableRangeRecord> implements Record1<Range<Integer>> {

    private static final long serialVersionUID = -1674655137;

    /**
     * Setter for <code>public.demographic_table_range.range</code>.
     */
    public void setRange(Range<Integer> value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.demographic_table_range.range</code>.
     */
    public Range<Integer> getRange() {
        return (Range<Integer>) get(0);
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<Range<Integer>> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<Range<Integer>> valuesRow() {
        return (Row1) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Range<Integer>> field1() {
        return DemographicTableRange.DEMOGRAPHIC_TABLE_RANGE.RANGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Range<Integer> component1() {
        return getRange();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Range<Integer> value1() {
        return getRange();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DemographicTableRangeRecord value1(Range<Integer> value) {
        setRange(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DemographicTableRangeRecord values(Range<Integer> value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DemographicTableRangeRecord
     */
    public DemographicTableRangeRecord() {
        super(DemographicTableRange.DEMOGRAPHIC_TABLE_RANGE);
    }

    /**
     * Create a detached, initialised DemographicTableRangeRecord
     */
    public DemographicTableRangeRecord(Range<Integer> range) {
        super(DemographicTableRange.DEMOGRAPHIC_TABLE_RANGE);

        set(0, range);
    }
}
