/*
 * This file is generated by jOOQ.
*/
package co.aisystem.demoJooq.api.db.tables.records;


import co.aisystem.demoJooq.api.db.tables.DemographicTableRange;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DemographicTableRangeRecord extends TableRecordImpl<DemographicTableRangeRecord> implements Record1<Object> {

    private static final long serialVersionUID = -606288762;

    /**
     * Setter for <code>public.demographic_table_range.range</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setRange(Object value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.demographic_table_range.range</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getRange() {
        return (Object) get(0);
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<Object> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<Object> valuesRow() {
        return (Row1) super.valuesRow();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public Field<Object> field1() {
        return DemographicTableRange.DEMOGRAPHIC_TABLE_RANGE.RANGE;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public Object component1() {
        return getRange();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public Object value1() {
        return getRange();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public DemographicTableRangeRecord value1(Object value) {
        setRange(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DemographicTableRangeRecord values(Object value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DemographicTableRangeRecord
     */
    public DemographicTableRangeRecord() {
        super(DemographicTableRange.DEMOGRAPHIC_TABLE_RANGE);
    }

    /**
     * Create a detached, initialised DemographicTableRangeRecord
     */
    public DemographicTableRangeRecord(Object range) {
        super(DemographicTableRange.DEMOGRAPHIC_TABLE_RANGE);

        set(0, range);
    }
}
