/*
 * This file is generated by jOOQ.
*/
package co.aisystem.demoJooq.api.db;


import co.aisystem.demoJooq.api.db.tables.Person;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.person</code>.
     */
    public static final Person PERSON = co.aisystem.demoJooq.api.db.tables.Person.PERSON;
}
