/*
 * This file is generated by jOOQ.
*/
package co.aisystem.demoJooq.api.db;


import co.aisystem.demoJooq.api.db.tables.EfitnessMemberMapping;
import co.aisystem.demoJooq.api.db.tables.Person;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index EFITNESS_MEMBER_MAPPING_PKEY = Indexes0.EFITNESS_MEMBER_MAPPING_PKEY;
    public static final Index PERSON_PKEY = Indexes0.PERSON_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index EFITNESS_MEMBER_MAPPING_PKEY = createIndex("efitness_member_mapping_pkey", EfitnessMemberMapping.EFITNESS_MEMBER_MAPPING, new OrderField[] { EfitnessMemberMapping.EFITNESS_MEMBER_MAPPING.ID }, true);
        public static Index PERSON_PKEY = createIndex("person_pkey", Person.PERSON, new OrderField[] { Person.PERSON.ID }, true);
    }
}
