/*
 * This file is generated by jOOQ.
*/
package co.aisystem.demoJooq.api.db;


import co.aisystem.demoJooq.api.db.tables.EfitnessMemberMapping;
import co.aisystem.demoJooq.api.db.tables.Person;
import co.aisystem.demoJooq.api.db.tables.records.EfitnessMemberMappingRecord;
import co.aisystem.demoJooq.api.db.tables.records.PersonRecord;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<EfitnessMemberMappingRecord, Long> IDENTITY_EFITNESS_MEMBER_MAPPING = Identities0.IDENTITY_EFITNESS_MEMBER_MAPPING;
    public static final Identity<PersonRecord, Long> IDENTITY_PERSON = Identities0.IDENTITY_PERSON;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<EfitnessMemberMappingRecord> EFITNESS_MEMBER_MAPPING_PKEY = UniqueKeys0.EFITNESS_MEMBER_MAPPING_PKEY;
    public static final UniqueKey<PersonRecord> PERSON_PKEY = UniqueKeys0.PERSON_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<EfitnessMemberMappingRecord, Long> IDENTITY_EFITNESS_MEMBER_MAPPING = createIdentity(EfitnessMemberMapping.EFITNESS_MEMBER_MAPPING, EfitnessMemberMapping.EFITNESS_MEMBER_MAPPING.ID);
        public static Identity<PersonRecord, Long> IDENTITY_PERSON = createIdentity(Person.PERSON, Person.PERSON.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<EfitnessMemberMappingRecord> EFITNESS_MEMBER_MAPPING_PKEY = createUniqueKey(EfitnessMemberMapping.EFITNESS_MEMBER_MAPPING, "efitness_member_mapping_pkey", EfitnessMemberMapping.EFITNESS_MEMBER_MAPPING.ID);
        public static final UniqueKey<PersonRecord> PERSON_PKEY = createUniqueKey(Person.PERSON, "person_pkey", Person.PERSON.ID);
    }
}
