/*
 * This file is generated by jOOQ.
*/
package co.aisystem.demoJooq.api.db.tables.records;


import co.aisystem.demoJooq.api.db.tables.EfitnessMemberMapping;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EfitnessMemberMappingRecord extends UpdatableRecordImpl<EfitnessMemberMappingRecord> implements Record3<Long, Long, Long> {

    private static final long serialVersionUID = -1706659933;

    /**
     * Setter for <code>public.efitness_member_mapping.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.efitness_member_mapping.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.efitness_member_mapping.e_fitness_id</code>.
     */
    public void setEFitnessId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.efitness_member_mapping.e_fitness_id</code>.
     */
    public Long getEFitnessId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.efitness_member_mapping.member_id</code>.
     */
    public void setMemberId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.efitness_member_mapping.member_id</code>.
     */
    public Long getMemberId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return EfitnessMemberMapping.EFITNESS_MEMBER_MAPPING.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return EfitnessMemberMapping.EFITNESS_MEMBER_MAPPING.E_FITNESS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return EfitnessMemberMapping.EFITNESS_MEMBER_MAPPING.MEMBER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getEFitnessId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getMemberId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getEFitnessId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getMemberId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EfitnessMemberMappingRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EfitnessMemberMappingRecord value2(Long value) {
        setEFitnessId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EfitnessMemberMappingRecord value3(Long value) {
        setMemberId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EfitnessMemberMappingRecord values(Long value1, Long value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EfitnessMemberMappingRecord
     */
    public EfitnessMemberMappingRecord() {
        super(EfitnessMemberMapping.EFITNESS_MEMBER_MAPPING);
    }

    /**
     * Create a detached, initialised EfitnessMemberMappingRecord
     */
    public EfitnessMemberMappingRecord(Long id, Long eFitnessId, Long memberId) {
        super(EfitnessMemberMapping.EFITNESS_MEMBER_MAPPING);

        set(0, id);
        set(1, eFitnessId);
        set(2, memberId);
    }
}
